title: webbserverprogrammering-1
description: Distansundervisning i Webbserverprogrammering 1 med anledning av covid-19
template:
  repo: webbserverprogrammering-1-template
  name: webbserverprogrammering-1
before:
  - type: createIssue
    title: Välkommen!
    body: new-issue.md
steps:
  - title: Introduktion
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
  - title: Uppgift Blog - Del 1 
    actions:
      - type: createIssue
        title: A new issue
        body: a-response-file.md
